title: Amateur Choirs Directory
description: A public platform for amateur choirs in the region
baseurl: "/quicanta"
url: ""         # "https://jllobera.github.io"

markdown: kramdown

collections:
  choirs:
    output: true
    permalink: /choirs/:slug/
  events:
    output: true
    permalink: /concerts/:slug/
  venues:
    output: true
    permalink: /venues/:slug/

defaults:
  - scope:
      path: ""
    values:
      layout: default
